### ISSUE TITLE
Will this work inside TravisCI ??

### ISSUE THREAD

**Issue by mitchellkrogza** [tst2005/git-timesync#4]
Hi I found this repo from the link you posted on https://gist.github.com/jeffery/1115504

That GIST does indeed work but I cannot get it to work inside a TravisCI container. Will your git-timesync work inside TravisCI ???

**Comment by tst2005** [comment]
Hello,

When I worked on git-timesync I focused on the Linux side.
You spoke about the original code (the GIST) that is not mine.
* Did you tried my git-timesync script ?
* What is your needs ?
* What is your error message ?

Best Regards,

**Comment by mitchellkrogza** [comment]
Thanks @tst2005 for the reply. 

My needs basically are within a TravisCI environment when it clones the repo it makes all file dates today's date and time / the time of the actual build. 

This is a GIT issue which in a local environment the GIST mentioned above does work to correct all the file dates and times but the GIST does not work inside TravisCI. 

So my actual needs inside TravisCI is after TravisCI clones the repo, to get the file dates correct as I would like to use that information of the date a file was last update inside my README.md file after each build so that users can see when a particular file was last updated. 

I have not tried your git-timesync yet inside TravisCI but I will give it a shot today on a test repo to see if I can get it working.

**Comment by mitchellkrogza** [comment]
@tst2005 tested inside TravisCI, still does not want to work. Unless I have used your script incorrectly. https://travis-ci.org/mitchellkrogza/CENTRAL-REPO.Dead.Inactive.Whitelisted.Domains.For.Hosts.Projects#L572-L672

**Comment by tst2005** [comment]
Some idea :
* change the shebang (from `#!/bin/sh` to `#!/bin/bash`) in case of a shell issue
* comment or remove the `set -e` line

In all case, can you get an error log from TravisCI ?
at which step did you run my script ?
It should really help to see an error message...

Regards,

**Comment by mitchellkrogza** [comment]
Thanks for your help @tst2005 I tried that, changed the shebang and commented out the set -e but still not getting the correct timestamps. 

If you look at the log lines below you can see it IS actually syncing timestamps but when complete they are not correct. I do an `ls -la` before and after running your script.

File Dates should be as follows on the second `ls -la`

```
Oct  6 07:08 DOMAINS-dead.txt
Oct  3 11:57 DOMAINS-re-active.txt
Oct  9 10:58 DOMAINS-whitelist.txt
Sep 29 17:06 IPV4-invalid.txt
Sep 29 16:57 IPV4-whitelist.txt
Sep 29 17:06 IPV6-invalid.txt
Sep 29 16:57 IPV6-whitelist.txt
```

But they all seem to be mostly Oct 6 / Oct 9 ?

Here's the log lines from the Travis build.

https://travis-ci.org/mitchellkrogza/CENTRAL-REPO.Dead.Inactive.Whitelisted.Domains.For.Hosts.Projects#L562-L689

I am running this in my script section of travis before I run anything else and I also make sure I am checked out on the master branch before running your script.

**Comment by tst2005** [comment]
1) I deciced to focus on one file : `DOMAINS-dead.txt`
I read on the log :
`-rw-rw-r-- 1 travis travis 777942 Oct 12 10:03 DOMAINS-dead.txt`
...
`!! DOMAINS-dead.txt (desync: 515417s, syncing...)`
...
`-rw-rw-r-- 1 travis travis 777942 Oct  6 10:53 DOMAINS-dead.txt`

My git-timesync change his time from `Oct 12` to `Oct  6`.

I check `now - 515417seconds` (`date -d '-515417sec'`) I truly get `Fri Oct  6 ...`
I think my script do his job.

* Do you get another result if you make it outsiide of TravisCL ?

If you make a `git log DOMAINS-dead.txt`, you should get the last commit dated from `Oct 6`.

**Important** :
 * My script have some limitations :
   * it is not able to sync time for directories (because git does not have metadata on directories)
   * it is not syncing file that are currently modified.

2) Now focused on `IPV4-invalid.txt`

If you think to get a issue on another file like `IPV4-invalid.txt`
You can see in the log 
`-rw-rw-r-- 1 travis travis     32 Oct 12 10:03 IPV4-invalid.txt`
...
`!! IPV4-invalid.txt (desync: 515417s, syncing...)`
...
`-rw-rw-r-- 1 travis travis     32 Oct  6 10:53 IPV4-invalid.txt`
...
`dos2unix: converting file /home/travis/build/mitchellkrogza/CENTRAL-REPO.Dead.Inactive.Whitelisted.Domains.For.Hosts.Projects/IPV4-invalid.txt to Unix format ...`

I think my git-timesync do his job but the `dos2unix` change the date.
if you want to make a modification without change the mtime you should make a workaround.

something like saving the mtime to restore it after.

```sh
dos2unix_preserve_time() {
  err=0
  for f in "$@"; do
    tmpfile="$(mktemp)" ;# need a temp file to store the time
    touch --reference "$1" "$tmpfile" ;# save the time on this temp file
    dos2unix "$1" || err=$?
    touch --reference "$tmpfile" "$1" ;# restore the time
    rm -f -- "$tmpfile" ;# remove the temp file
  done
  return $err
}
```

**Comment by mitchellkrogza** [comment]
Thanks @tst2005 I run the git timesync before I even run the Dos2Unix commands. On my local machine macOS I ran `git log DOMAINS-dead.txt` and got the correct date.

```
git log DOMAINS-dead.txt
commit beb62745f1867f40674c95d0c3fc4f28828e4c2a
Author: Travis <mitchellkrog@gmail.com>
Date:   Thu Oct 5 19:59:50 2017 +0200

    V1.2017.10.324 [ci skip]
```

I will add some git log commands into the script to try and see what TravisCI is seeing

I also ran on my local desktop

```
git log IPV4-invalid.txt
commit 3b3d83e022b166abe533f9cf5aca231782273afc
Author: Travis <mitchellkrog@gmail.com>
Date:   Fri Sep 29 17:04:11 2017 +0200

    V1.2017.09.301 [ci skip]
```

**Comment by mitchellkrogza** [comment]
@tst2005 as you can see from this latest log, TravisCI is doing something VERY strange and funny when it clones the repo. I think this is a TravisCI bug and will report it to them. Note that the 2 git log commands I run, run before any other commands in my script. Travis is somehow modifying the log files of the repo it clones ??

https://travis-ci.org/mitchellkrogza/CENTRAL-REPO.Dead.Inactive.Whitelisted.Domains.For.Hosts.Projects#L573-L581

I will report this to TravisCI support and see what they say.

**Comment by tst2005** [comment]
@mitchellkrogza do you have something new about your issue ?

**Comment by mitchellkrogza** [comment]
Nothing new @tst2005 closing
