### ISSUE TITLE
Does not work on Git Bash

### ISSUE THREAD

**Issue by dmotte** [tst2005/git-timesync#5]
Hi! Thanks for creating this script :)

Unfortunately, it does not work on Git Bash on Windows 10 (`Unknown Operating System to perform timestamp update`).
In fact I think it could work, but it does not allow execution since it doesn't recognize the OS.

If it's ok for you, I can try to figure it out when i have some free time and then I'll make a pull request. Let me know :wink:

**Comment by tst2005** [comment]
Now it should run on Git Bash on Windows.
I think we can close this issue.
Thanks for your feedback!

**Comment by tst2005** [comment]
@dmotte,

To make a proper WSL support,
- I would like to know if the `uname` command is available on WSL ?
- if yes, what is the value returned by `uname -s` ?
Thanks in advance

**Comment by dmotte** [comment]
Hi @tst2005,

I have recently switched to Linux, but I still have an old **Windows 10 laptop** with **WSL 1** available. Unfortunately, it does not support WSL 2. Anyway, this is the output you asked for:

```
root@dmottepc:/mnt/c/Users/Motte# uname -s
Linux
```

It makes sense to me. In fact, WSL is basically real Linux inside Windows.

BTW, this issue was about Git Bash, not WSL :wink: worth mentioning

Thanks for your time

**Comment by tst2005** [comment]
Oh ok ... but the issue mention the "Unknown Operating System to perform timestamp update" error.
This error only happens when `uname` (not `uname -s` like asked yesterday) returns a value different than "Linux", "MINGW64", "Darwin", "FreeBSD".
So I wonder that is this value ?!

- Can you tell me what is returned by the `uname` command with "GIT Bash" and with "WSL" ?
It will help me a lot to support them ;-)

Thanks!

**Comment by dmotte** [comment]
Yes, of course :) here all the possible combinations of commands / platforms you need

On **Git Bash**:

```
Motte@dmottepc MINGW64 ~
$ uname
MINGW64_NT-10.0-17763

Motte@dmottepc MINGW64 ~
$ uname -s
MINGW64_NT-10.0-17763
```

On **WSL 1**:

```
root@dmottepc:/mnt/c/Users/Motte# uname
Linux
root@dmottepc:/mnt/c/Users/Motte# uname -s
Linux
```

Hope this will be useful

**Comment by tst2005** [comment]
Thanks for your feedback.
The result are not what I expected, then I keep digging with the issue you got...

All `uname` or `uname -s` returns proper values.

The only case where you can get the "Unknown Operating System to perform timestamp update" is ... if `$OS` variable is defined.

- Can you try a `echo $OS` in GIT Bash ? 
- also in WSL (if you can, just in case) ?

I chose the `OS` variable name because it is not defined on Linux, I didn't think it can be already defined!
If the `echo $OS` show you a value (that I suppose), i will fix the git-timesync script by using another variable name to enforce the detection.

Regards,

**Comment by dmotte** [comment]
Hey, I think you don't have to do this :sweat_smile: in fact, the issue was first closed because you fixed the code.

BTW, you ask, I answer :wink:

On **Git Bash**:

```
Motte@dmottepc MINGW64 ~
$ echo $OS
Windows_NT
```

On **WSL 1**:

```
root@dmottepc:/mnt/c/Users/Motte# echo $OS

```

Like you said, the OS env var is not defined in WSL, but it is defined is Git Bash.

**Comment by tst2005** [comment]
Perfect, that is an expected result!

It made a fix to use another variable name:
`GIT_TIMESYNC_FORCE_UNAME` instead of `OS`.
Thanks for you feedback.

Because I'm feel less lonely using git-timesync, I decided to release this version as a 1.0.0 ;-)
Have fun!

**Comment by dmotte** [comment]
You are not alone, this is useful man.

Every single line of code we share could be useful to someone one day. That's the beauty of open-source!

Thanks for your work :)

**Comment by tst2005** [comment]
Thanks for your kindness! I don't get this kind of message often.
Regards,
